name: datawiz
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  syncfusion_flutter_charts: ^18.4.48
  pie_chart: ^5.0.0
  horizontal_data_table: ^2.5.2
  shared_preferences: ^2.0.3
  vertical_card_pager: ^1.4.0
  syncfusion_flutter_datagrid: ^18.4.49-beta
  syncfusion_flutter_core: ^18.4.49
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - Assets/Images/newschannel/
    - Assets/Images/Background/
    - Assets/Images/getStartedImages/
    - Assets/Images/Icons/
    - Assets/Images/IndiaImages/

  fonts:
    - family: SplashFont
      fonts:
        - asset: Assets/font/NewTegomin-Regular.ttf